swagger: "2.0"
info:
  title: Transaction API
  description: This is the propostion of API model for transaction services of the Argent Bank compagny in order to allow the client to visualize transaction, transaction in detail and add, modify or delete information about transaction.
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
tags:
  - name: User Transaction
schemes:
  - http
paths:
  /user/transactions:
    get:
      tags:
        - User Transaction
      summary: User's Transactions of current month
      description: API for a user transaction
      parameters:
        - name: Dates
          in: body
          description: Start and end of transactions to display
          required: true
          schema:
            $ref: "#/definitions/TransactionsDate"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction Successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "404":
          description: "Not Found"
        "500":
          description: Internal Server Error
      security:
        - Bearer: []
  /user/transactions/{id}/details:
    get:
      tags:
        - User Transaction
      summary: Transaction Details
      description: "Transaction details: type, category and notes"
      produces:
        - application/json
      parameters:
        - name: Autorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: id
          in: path
          description: Transaction ID
          required: true
          type: string
      responses:
        "200":
          description: Transaction Successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid values
        "500":
          description: Internal Server Error
      security:
        - Bearer: []
    post:
      tags:
        - User Transaction
      summary: Transaction Details
      description: API to add a user's transaction details
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Transaction ID
          required: true
          type: string
      responses:
        "200":
          description: Transaction Successfully
          schema:
            $ref: "#/definitions/Details"
        "400":
          description: Invalid values
        "500":
          description: Internal Server Error
      security:
        - Bearer: []
    put:
      tags:
        - User Transaction
      summary: Transaction Details
      description: API for fetching a user transaction details
      parameters:
        - name: id
          in: path
          description: id of the transaction needed to be updated
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction Successfully
          schema:
            $ref: "#/definitions/Details"
        "400":
          description: Invalid Fields
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
        - Bearer: []
    delete:
      tags:
        - User Transaction
      summary: API for delete a transaction details
      parameters:
        - name: id
          in: path
          description: id of the transaction needed to be delete
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction Successfully
          schema:
            $ref: "#/definitions/Details"
        "400":
          description: Invalid Fields
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
        - Bearer: []
  /user/transactions/{id}/category:
    put:
      tags:
        - User Transaction
      summary: Transaction Category
      description: API for updating a transaction category
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: Category
          description: Transaction updated category
          schema:
            $ref: "#/definitions/Category"
          required: true
        - name: id
          in: path
          description: id of the transaction needed to be updated
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Category updated successully
          schema:
            $ref: "#/definitions/CategoryUpdated"
        "400":
          description: Invalid Fields
        "401":
          description: UnAutorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
        - Bearer: []
  /user/transactions/{id}/note:
    put:
      tags:
        - User Transaction
      summary: Update Note
      description: API for updating a note
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: Note
          description: Transaction updated note
          schema:
            $ref: "#/definitions/Note"
          required: true
        - name: id
          in: path
          description: id of the transaction needed to be updated
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Note updated successfully
          schema:
            $ref: "#/definitions/NoteUpdated"
        "400":
          description: Invalid Fields
        "401":
          description: UnAutorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
        - Bearer: []
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          date:
            type: string
          description:
            type: string
          amount:
            type: number
          balance:
            type: number
  Details:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          transactionType:
            type: string
          category:
            type: string
          notes:
            type: string
  CategoryUpdated:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
      id:
        type: string
      categoryUpdated:
        type: string
  NoteUpdated:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          noteUpdated:
            type: string
  Category:
    type: object
    properties:
      category:
        type: string
  Note:
    type: object
    properties:
      note:
        type: string
  TransactionsDate:
    type: object
    properties:
      from:
        type: string
        format: date
        description: start date of transactions recovery (one month ago)
      to:
        type: string
        format: date
        description: end date of transaction recovery (today)
